name: X Tweet Scheduler

on:
  schedule:
    # Her 5 dakikada bir tetiklenir; doğru dakikada paylaşımı script karar verir
    - cron: '* * * * *'
  workflow_dispatch: {}

# Eşzamanlı paralel çalışmaları engelle (çifte paylaşımı önler)
concurrency:
  group: tweet-scheduler
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # (Opsiyonel) Depo yapısını görmek için
      - name: Debug tree
        run: ls -R

      - name: Restore previous state (if exists)
        uses: actions/cache@v4
        with:
          path: src/state.json
          # Dal ve işletim sistemi bazlı anahtar; gerektiğinde -v2 gibi son ekle reset için
          key: state-${{ runner.os }}-${{ github.ref_name }}
          restore-keys: |
            state-${{ runner.os }}-${{ github.ref_name }}
            state-

      - name: Run scheduler
        env:
          TW_CONSUMER_KEY: ${{ secrets.TW_CONSUMER_KEY }}
          TW_CONSUMER_SECRET: ${{ secrets.TW_CONSUMER_SECRET }}
          TW_ACCESS_TOKEN: ${{ secrets.TW_ACCESS_TOKEN }}
          TW_ACCESS_TOKEN_SECRET: ${{ secrets.TW_ACCESS_TOKEN_SECRET }}
          # Settings → Actions → Variables içinde DRY_RUN=true ise deneme modunda çalışır
          DRY_RUN: ${{ vars.DRY_RUN || 'false' }}
        run: |
          python -u src/poster.py

      - name: Show state after run
        if: always()
        run: |
          if [ -f src/state.json ]; then
            echo "----- state.json -----"
            cat src/state.json
          else
            echo "state.json yok"
          fi

      - name: Persist state
        if: always()
        uses: actions/cache/save@v4
        with:
          path: src/state.json
          key: state-${{ runner.os }}-${{ github.ref_name }}
