name: X Tweet Scheduler

on:
  schedule:
    # Her 5 dakikada bir tetiklenir; doğru dakikayı script kontrol eder
    - cron: '*/5 * * * *'
  workflow_dispatch: {}
concurrency:
  group: tweet-scheduler
  cancel-in-progress: true
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Restore state (if exists)
        uses: actions/cache@v4
        with:
          path: src/state.json
          key: state-${{ github.run_id }}
          restore-keys: |
            state-

      - name: Run scheduler
        env:
          TW_CONSUMER_KEY: ${{ secrets.TW_CONSUMER_KEY }}
          TW_CONSUMER_SECRET: ${{ secrets.TW_CONSUMER_SECRET }}
          TW_ACCESS_TOKEN: ${{ secrets.TW_ACCESS_TOKEN }}
          TW_ACCESS_TOKEN_SECRET: ${{ secrets.TW_ACCESS_TOKEN_SECRET }}
          DRY_RUN: ${{ vars.DRY_RUN || 'false' }}
        run: |
          python -u src/poster.py

      - name: Persist state
        if: always()
        uses: actions/cache/save@v4
        with:
          path: src/state.json
          key: state-${{ github.run_id }}
