name: X Tweet Scheduler

on:
  # GitHub Actions en erken 5 dakikada bir tetikler
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
    inputs:
      FORCE_POST_NOW:
        description: "Zaman kontrolünü atla (hemen gönder)"
        type: boolean
        required: false
        default: false
      DRY_RUN:
        description: "Dry run (gerçek tweet atma)"
        type: boolean
        required: false
        default: false

permissions:
  contents: read

# Aynı dal için eşzamanlı run'ların çakışmasını önleyelim
concurrency:
  group: x-tweet-scheduler-${{ github.ref }}
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Bir önceki state.json varsa geri yükle
      - name: Restore previous state (if exists)
        uses: actions/cache@v4
        with:
          path: src/state.json
          key: state-${{ runner.os }}-${{ github.ref_name }}
          restore-keys: |
            state-${{ runner.os }}-${{ github.ref_name }}
            state-

      - name: Run scheduler
        env:
          # X (Twitter) API anahtarları
          TW_CONSUMER_KEY: ${{ secrets.TW_CONSUMER_KEY }}
          TW_CONSUMER_SECRET: ${{ secrets.TW_CONSUMER_SECRET }}
          TW_ACCESS_TOKEN: ${{ secrets.TW_ACCESS_TOKEN }}
          TW_ACCESS_TOKEN_SECRET: ${{ secrets.TW_ACCESS_TOKEN_SECRET }}

          # Manuel tetiklerde input; cron tetiklerinde 'false'
          DRY_RUN: ${{ github.event_name == 'workflow_dispatch' && inputs.DRY_RUN || 'false' }}
          FORCE_POST_NOW: ${{ github.event_name == 'workflow_dispatch' && inputs.FORCE_POST_NOW || 'false' }}

          # >>> Cron gecikmesine tolerans (saniye) — poster.py default'u bununla ezilecek
          WINDOW_SECONDS: "180"
        run: |
          python -u src/poster.py

      - name: Show state after run
        run: |
          if [ -f src/state.json ]; then
            echo "----- state.json -----"
            cat src/state.json
          else
            echo "state.json yok"
          fi

      # Güncel state'i sakla
      - name: Persist state
        if: always()
        uses: actions/cache/save@v4
        with:
          path: src/state.json
          key: state-${{ runner.os }}-${{ github.ref_name }}
