name: X Tweet Scheduler

on:
  schedule:
    - cron: "* * * * *"   # her dakika tetiklenecek
  workflow_dispatch:
    inputs:
      override:
        description: "Zaman kontrolünü atla (FORCE_POST_NOW)"
        type: boolean
        default: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Restore previous state (if exists)
        uses: actions/cache@v4
        with:
          path: src/state.json
          key: state-${{ runner.os }}-${{ github.ref_name }}
          restore-keys: |
            state-${{ runner.os }}-${{ github.ref_name }}
            state-

      - name: Run scheduler
        env:
          TW_CONSUMER_KEY: ${{ secrets.TW_CONSUMER_KEY }}
          TW_CONSUMER_SECRET: ${{ secrets.TW_CONSUMER_SECRET }}
          TW_ACCESS_TOKEN: ${{ secrets.TW_ACCESS_TOKEN }}
          TW_ACCESS_TOKEN_SECRET: ${{ secrets.TW_ACCESS_TOKEN_SECRET }}
          DRY_RUN: false
          TZ: Europe/Istanbul
          WINDOW_SECONDS: "60"
          FORCE_POST_NOW: ${{ github.event.inputs.override || 'false' }}
        run: python -u src/poster.py

      - name: Show state after run
        if: always()
        run: |
          if [ -f src/state.json ]; then
            echo "----- state.json -----"
            cat src/state.json
          else
            echo "state.json yok"
          fi

      - name: Persist state
        if: always()
        uses: actions/cache/save@v4
        with:
          path: src/state.json
          key: state-${{ runner.os }}-${{ github.ref_name }}