name: X Tweet Scheduler

on:
  # Otomatik tetikleme (ör. her 5 dk). İsterseniz 10 dk yapın: "*/10 * * * *"
  schedule:
    - cron: "*/5 * * * *"
  # Manuel tetikleme ve ayarlar
  workflow_dispatch:
    inputs:
      force_post_now:
        description: "Zaman kontrolünü atla (hemen gönder)"
        type: boolean
        default: false
      dry_run:
        description: "Deneme modu (tweet atmaz)"
        type: boolean
        default: false
      window_seconds:
        description: "Eşleşme toleransı (sn) — öneri: 600"
        type: number
        default: 600

# İsteğe bağlı: içerik izinleri sadece okunur. (Daha önce hatayı 'permissions' yanlış yerde kullanmaktan alıyordunuz.)
permissions:
  contents: read

# Aynı anda birden fazla run çakışmasın
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest

    # ENV kaynakları hiyerarşisi:
    # 1) Manuel çalıştırmada ekran girdileri
    # 2) Repo → Settings → Actions → Variables (vars.DRY_RUN / vars.WINDOW_SECONDS)
    # 3) Varsayılanlar: DRY_RUN=false, WINDOW_SECONDS=600
    env:
      DRY_RUN: ${{ (github.event_name == 'workflow_dispatch' && inputs.dry_run) || vars.DRY_RUN || 'false' }}
      FORCE_POST_NOW: ${{ (github.event_name == 'workflow_dispatch' && inputs.force_post_now) || vars.FORCE_POST_NOW || 'false' }}
      WINDOW_SECONDS: ${{ (github.event_name == 'workflow_dispatch' && inputs.window_seconds) || vars.WINDOW_SECONDS || 600 }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Restore previous state (if exists)
        uses: actions/cache@v4
        with:
          path: src/state.json
          key: state-${{ runner.os }}-${{ github.ref_name }}
          restore-keys: |
            state-${{ runner.os }}-${{ github.ref_name }}
            state-

      - name: Run scheduler
        run: python -u src/poster.py

      - name: Show state after run
        if: always()
        run: |
          if [ -f src/state.json ]; then
            echo "----- state.json -----"
            cat src/state.json
          else
            echo "state.json yok"
          fi

      - name: Persist state
        if: always()
        uses: actions/cache/save@v4
        with:
          path: src/state.json
          key: state-${{ runner.os }}-${{ github.ref_name }}
